@include('shared.validation')
<form class="asset-form" method="POST" action="{{ $outlookAccount->exists ? route('outlook-accounts.update',$outlookAccount) : route('outlook-accounts.store') }}">@csrf @if($outlookAccount->exists)@method('PUT')@endif
<section class="form-section secret-section"><div class="section-heading"><div><p class="eyebrow">Outlook externo</p><h2>Cuenta y servidores</h2></div><span class="security-label">Dato protegido</span></div>
<div class="form-grid"><label><span>Empleado registrado</span><select name="employee_id"><option value="">Sin vincular</option>@foreach($employees as $employee)<option value="{{ $employee->id }}" @selected((string) old('employee_id', $outlookAccount->employee_id) === (string) $employee->id)>{{ $employee->full_name }}{{ $employee->department ? ' - '.$employee->department : '' }}</option>@endforeach</select></label></div>
<div class="form-grid three-columns"><label><span>Correo *</span><input type="email" name="correo" required maxlength="150" value="{{ old('correo',$outlookAccount->correo) }}" autocomplete="off"></label><label class="password-field"><span>Contraseña {{ $outlookAccount->exists ? '(vacia conserva la actual)' : '*' }}</span><div class="password-input-wrap"><input id="outlook-password" type="password" name="contraseña" {{ $outlookAccount->exists ? '' : 'required' }} maxlength="255" autocomplete="new-password"><button class="password-toggle" type="button" aria-label="Mostrar contraseña" aria-pressed="false" data-password-toggle="outlook-password"><i class="bi bi-eye"></i></button></div></label><label><span>Estado *</span><select name="estatus">@foreach(['ACTIVA','BAJA'] as $option)<option value="{{ $option }}" @selected(old('estatus',$outlookAccount->estatus ?: 'ACTIVA') === $option)>{{ $option }}</option>@endforeach</select></label><label><span>Servidor de entrada</span><input name="servidor_entrada" maxlength="255" value="{{ old('servidor_entrada',$outlookAccount->servidor_entrada ?: 'mail.totalground.com') }}"></label><label><span>Puerto de entrada</span><input name="puerto_entrada" maxlength="20" value="{{ old('puerto_entrada',$outlookAccount->puerto_entrada ?: '995') }}"></label><label class="check-option"><input type="checkbox" name="ssl_entrada" value="1" @checked(old('ssl_entrada', $outlookAccount->ssl_entrada ?? true))><span>SSL de entrada</span></label><label><span>Servidor de salida</span><input name="servidor_salida" maxlength="255" value="{{ old('servidor_salida',$outlookAccount->servidor_salida ?: 'mail.totalground.com') }}"></label><label><span>Puerto de salida</span><input name="puerto_salida" maxlength="20" value="{{ old('puerto_salida',$outlookAccount->puerto_salida ?: '465') }}"></label><label><span>Cifrado de salida</span><input name="cifrado_salida" maxlength="50" value="{{ old('cifrado_salida',$outlookAccount->cifrado_salida ?: 'SSL/TLS') }}"></label></div>
<label class="textarea-field"><span>Comentarios</span><textarea name="comentarios">{{ old('comentarios',$outlookAccount->comentarios) }}</textarea></label></section><footer class="form-footer"><a class="button button-secondary" href="{{ $outlookAccount->exists ? route('outlook-accounts.show',$outlookAccount) : route('credentials.index',['type'=>'outlook']) }}">Cancelar</a><button class="button button-primary">{{ $outlookAccount->exists ? 'Guardar cambios' : 'Registrar correo' }}</button></footer></form>
@push('scripts')
<script>
document.querySelectorAll('[data-password-toggle]').forEach((button) => button.addEventListener('click', () => {
    const input = document.getElementById(button.dataset.passwordToggle);
    if (!input) return;
    const visible = input.type === 'password';
    input.type = visible ? 'text' : 'password';
    button.setAttribute('aria-pressed', visible ? 'true' : 'false');
    button.setAttribute('aria-label', visible ? 'Ocultar contraseña' : 'Mostrar contraseña');
    button.innerHTML = `<i class="bi ${visible ? 'bi-eye-slash' : 'bi-eye'}"></i>`;
}));
</script>
@endpush
