@extends('layouts.app')
@section('title','Perifericos') @section('page-title','Perifericos')
@section('content')
<section class="page-intro compact"><div><p class="eyebrow">Accesorios y perifericos</p><h2>{{ $peripherals->total() }} registros encontrados</h2><p>Consulta asignaciones, equipos vinculados y existencias.</p></div><div class="page-actions"><form method="GET" class="search-form"><label class="sr-only" for="search">Buscar perifericos</label><input id="search" name="search" value="{{ $search }}" placeholder="Articulo, serie, empleado, computadora..."><button class="button button-secondary">Buscar</button>@if($search !== '')<a class="button button-secondary" href="{{ route('peripherals.index') }}">Limpiar</a>@endif</form><x-recent-filter />@can('create',\App\Models\Peripheral::class)<a class="button button-primary" href="{{ route('peripherals.create') }}">Nuevo periferico</a>@endcan</div></section>
<section class="panel table-panel"><div class="table-scroll"><table><thead><tr><th>Articulo</th><th>Marca</th><th>Cant.</th><th>Computadora</th><th>Asignado a</th><th data-filterable="true">Estado</th><th>Folio</th><th></th></tr></thead><tbody>
@forelse($peripherals as $peripheral)<tr><td><strong>{{ $peripheral->name }}</strong><small>{{ $peripheral->category ?: 'General' }} · {{ $peripheral->serial ?: 'Sin serie' }}</small></td><td>{{ $peripheral->brand ?: '-' }}</td><td>{{ $peripheral->quantity }}</td><td>@if($peripheral->computer)<a class="relation-link" href="{{ route('computers.show',$peripheral->computer) }}">{{ $peripheral->computer->name }}</a>@else - @endif</td><td>{{ $peripheral->assigned_name ?: 'Sin asignar' }}</td><td><span class="status">{{ $peripheral->status }}</span></td><td>{{ $peripheral->code ?: '-' }}</td><td><div class="row-actions"><a class="table-action" href="{{ route('peripherals.show',$peripheral) }}">Detalles</a>@can('update',$peripheral)<a class="table-action secondary" href="{{ route('peripherals.edit',$peripheral) }}">Editar</a>@endcan</div></td></tr>
@empty<tr><td colspan="8" class="empty">No hay resultados para esta busqueda.</td></tr>@endforelse</tbody></table></div>
@if($peripherals->hasPages())<nav class="pagination">@if($peripherals->onFirstPage())<span>Anterior</span>@else<a href="{{ $peripherals->previousPageUrl() }}">Anterior</a>@endif<strong>Pagina {{ $peripherals->currentPage() }} de {{ $peripherals->lastPage() }}</strong>@if($peripherals->hasMorePages())<a href="{{ $peripherals->nextPageUrl() }}">Siguiente</a>@else<span>Siguiente</span>@endif</nav>@endif
</section>@endsection
