@include('shared.validation')
@php
    $licenseTypes = config('inventory.catalogs.license_types');
    $licenseStatuses = config('inventory.catalogs.license_statuses');
    $selectedType = old('type', $softwareLicense->type);
    $selectedStatus = old('status', $softwareLicense->status ?: 'Activa');
    if ($selectedType && ! in_array($selectedType, $licenseTypes, true)) $licenseTypes[] = $selectedType;
    if ($selectedStatus && ! in_array($selectedStatus, $licenseStatuses, true)) $licenseStatuses[] = $selectedStatus;
@endphp
<form class="asset-form" method="POST" action="{{ $softwareLicense->exists ? route('software-licenses.update',$softwareLicense) : route('software-licenses.store') }}">@csrf @if($softwareLicense->exists)@method('PUT')@endif
<section class="form-section secret-section"><div class="section-heading"><div><p class="eyebrow">Software y servicios</p><h2>Datos de licencia</h2></div><span class="security-label">Llaves protegidas</span></div><div class="form-grid three-columns"><label><span>Nombre *</span><input name="name" required maxlength="150" value="{{ old('name',$softwareLicense->name) }}"></label><label><span>Tipo</span><select name="type"><option value="">Seleccionar</option>@foreach($licenseTypes as $option)<option value="{{ $option }}" @selected($selectedType === $option)>{{ $option }}</option>@endforeach</select></label><label><span>Proveedor</span><input name="vendor" maxlength="100" value="{{ old('vendor',$softwareLicense->vendor) }}"></label><label><span>Estado *</span><select name="status" required>@foreach($licenseStatuses as $option)<option value="{{ $option }}" @selected($selectedStatus === $option)>{{ $option }}</option>@endforeach</select></label><label><span>Vencimiento</span><input type="date" name="expiration_date" value="{{ old('expiration_date',$softwareLicense->expiration_date?->format('Y-m-d')) }}"></label><label><span>Enlace</span><input type="url" name="link" value="{{ old('link',$softwareLicense->link) }}"></label><label><span>Usuario / Llave {{ $softwareLicense->exists ? '(vacio conserva el actual)' : '' }}</span><input type="password" name="key_value" autocomplete="new-password"></label><label><span>Contrasena {{ $softwareLicense->exists ? '(vacia conserva la actual)' : '' }}</span><input type="password" name="password" maxlength="255" autocomplete="new-password"></label></div><label class="textarea-field"><span>Comentarios</span><textarea name="comments">{{ old('comments',$softwareLicense->comments) }}</textarea></label></section><footer class="form-footer"><a class="button button-secondary" href="{{ $softwareLicense->exists ? route('software-licenses.show',$softwareLicense) : route('credentials.index',['type'=>'licenses']) }}">Cancelar</a><button class="button button-primary">{{ $softwareLicense->exists ? 'Guardar cambios' : 'Registrar licencia' }}</button></footer></form>
