<?php
namespace Tests\Feature;
use App\Models\CalendarReminder; use App\Models\FileCatalog; use App\Models\GalleryItem; use App\Models\Note; use App\Models\Tutorial; use App\Models\User; use Illuminate\Foundation\Testing\RefreshDatabase; use Illuminate\Http\UploadedFile; use Illuminate\Support\Facades\Hash; use Illuminate\Support\Facades\Process; use Illuminate\Support\Facades\Storage; use Tests\TestCase;
class ProductivityAndLibraryTest extends TestCase
{
 use RefreshDatabase;
 public function test_support_can_manage_notes_and_reminders():void{$u=$this->user('soporte');$this->actingAs($u)->post(route('notes.store'),['title'=>'Procedimiento Zenith','content'=>'Contenido interno'])->assertSessionHasNoErrors();$note=Note::firstOrFail();$this->getJson(route('search.suggestions',['q'=>'Zenith']))->assertOk()->assertJsonPath('results.0.url',route('notes.show',$note));$this->post(route('calendar.store'),['event_date'=>'2026-08-20','title'=>'Revision Zenith','color'=>'#e30613','is_done'=>1])->assertSessionHasNoErrors();$reminder=CalendarReminder::firstOrFail();$this->get(route('calendar.index',['month'=>'2026-08']))->assertOk()->assertSee('Revision Zenith');$this->assertTrue($reminder->is_done);}
 public function test_global_search_includes_all_library_types():void{Tutorial::create(['title'=>'Manual Quasar']);GalleryItem::create(['title'=>'Foto Nebula','filename'=>'x.jpg']);FileCatalog::create(['original_name'=>'Instalador Pulsar.exe','file_path'=>'x']);$this->actingAs($this->user('consulta'));$this->getJson(route('search.suggestions',['q'=>'Quasar']))->assertJsonPath('results.0.type','Tutorial');$this->getJson(route('search.suggestions',['q'=>'Nebula']))->assertJsonPath('results.0.type','Galeria');$this->getJson(route('search.suggestions',['q'=>'Pulsar']))->assertJsonPath('results.0.type','Archivo');}
 public function test_tutorial_pagination_uses_compact_navigation():void{foreach(range(1,19) as $number)Tutorial::create(['title'=>'Tutorial '.$number]);$this->actingAs($this->user('consulta'));$this->get(route('tutorials.index'))->assertOk()->assertSee('Pagina 1 de 2')->assertSee('Siguiente')->assertDontSee('<svg',false);$this->get(route('tutorials.index',['page'=>2]))->assertOk()->assertSee('Pagina 2 de 2')->assertSee('Anterior');}
 public function test_tutorial_pdf_can_be_previewed_inline_from_its_detail():void{Storage::fake('local');Storage::disk('local')->put('library/tutorials/manual.pdf',"%PDF-1.4\n%%EOF");$tutorial=Tutorial::create(['title'=>'Manual visible','content_url'=>'laravel-local:library/tutorials/manual.pdf']);$this->actingAs($this->user('consulta'));$this->get(route('tutorials.show',$tutorial))->assertOk()->assertSee(route('tutorials.preview',$tutorial),false)->assertSee('tutorial-pdf-viewer');$this->get(route('tutorials.preview',$tutorial))->assertOk()->assertHeader('content-type','application/pdf');}
 public function test_general_files_keep_a_descriptive_and_original_name_with_quick_actions():void{Storage::fake('local');$this->actingAs($this->user('soporte'))->post(route('files.store'),['alias_name'=>'Instalador de soporte remoto','file'=>UploadedFile::fake()->create('anydesk-original.exe',128,'application/octet-stream'),'comments'=>'Uso interno'])->assertSessionHasNoErrors();$file=FileCatalog::firstOrFail();$this->assertSame('Instalador de soporte remoto',$file->alias_name);$this->assertSame('anydesk-original.exe',$file->original_name);$this->get(route('files.index'))->assertOk()->assertSee('Instalador de soporte remoto')->assertSee('Archivo original: anydesk-original.exe')->assertSee('bi-eye')->assertSee('bi-download')->assertSee(route('files.download',$file),false);$this->get(route('files.edit',$file))->assertOk()->assertSee('Nombre descriptivo')->assertSee('anydesk-original.exe');$this->get(route('files.download',$file))->assertDownload('anydesk-original.exe');}
 public function test_consultation_cannot_modify_productivity_records_or_view_backups():void{$n=Note::create(['title'=>'Bloqueada']);$r=CalendarReminder::create(['event_date'=>'2026-08-20','title'=>'Bloqueado']);$this->actingAs($this->user('consulta'));$this->get(route('notes.create'))->assertForbidden();$this->delete(route('notes.destroy',$n))->assertForbidden();$this->get(route('calendar.edit',$r))->assertForbidden();$this->get(route('backups.index'))->assertForbidden();}
 public function test_admin_can_generate_private_database_backup():void{Storage::fake('local');Process::fake(['*'=>Process::result(output:'-- SQL BACKUP')]);$this->actingAs($this->user('admin'))->post(route('backups.store'))->assertSessionHasNoErrors();$run=\App\Models\BackupRun::firstOrFail();$this->assertStringStartsWith('laravel-local:backups/',$run->filename);Storage::disk('local')->assertExists(substr($run->filename,14));}
 private function user(string $role):User{return User::create(['username'=>'productivity_'.$role.'_'.User::count(),'password'=>Hash::make('password'),'full_name'=>'Usuario '.$role,'role'=>$role]);}
}
