@extends('layouts.app')
@section('title', 'Red')
@section('page-title', 'Gestion de red')
@section('content')
<section class="page-intro compact"><div><p class="eyebrow">Infraestructura y accesos</p><h2>Red empresarial</h2><p>Dispositivos conectados, usuarios WatchGuard y redes inalambricas.</p></div><div class="page-actions"><details class="network-notice-menu"><summary class="button button-secondary"><i class="bi bi-file-earmark-text" aria-hidden="true"></i> Aviso Red Externos <i class="bi bi-chevron-down" aria-hidden="true"></i></summary><nav aria-label="Opciones del aviso"><a href="{{ route('network.acceptable-use.preview', ['preview' => 1]) }}" target="_blank" rel="noopener"><i class="bi bi-eye" aria-hidden="true"></i> Vista previa</a><a href="{{ route('network.acceptable-use.download', ['with_letterhead' => 1]) }}"><i class="bi bi-file-earmark-arrow-down" aria-hidden="true"></i> Descargar con membrete</a><a href="{{ route('network.acceptable-use.download', ['with_letterhead' => 0]) }}"><i class="bi bi-file-earmark-text" aria-hidden="true"></i> Descargar sin membrete</a></nav></details><x-recent-filter />@if($type === 'devices')@can('create', \App\Models\NetworkDevice::class)<a class="button button-primary" href="{{ route('network-devices.create') }}">Nuevo dispositivo</a>@endcan @elseif($type === 'watchguard')@can('create', \App\Models\WatchguardUser::class)<a class="button button-primary" href="{{ route('watchguard-users.create') }}">Nuevo usuario</a>@endcan @else @can('create', \App\Models\EnterpriseNetwork::class)<a class="button button-primary" href="{{ route('enterprise-networks.create') }}">Nueva red</a>@endcan @endif</div></section>
<section class="stats-grid network-stats"><article><span>Dispositivos</span><strong>{{ $stats['devices'] }}</strong><small>{{ $stats['active'] }} activos</small></article><article><span>WatchGuard</span><strong>{{ $stats['watchguard'] }}</strong><small>Usuarios configurados</small></article><article><span>Redes</span><strong>{{ $stats['networks'] }}</strong><small>SSID registrados</small></article></section>
<section class="panel table-panel">
    <x-module-tabs :active="$type" label="Area de red" :tabs="[
        'devices' => ['label'=>'Dispositivos', 'description'=>'Switches, routers y puntos de acceso', 'count'=>$stats['devices'], 'icon'=>'bi-router', 'url'=>route('network.index',['type'=>'devices'])],
        'watchguard' => ['label'=>'WatchGuard', 'description'=>'Usuarios y accesos autorizados', 'count'=>$stats['watchguard'], 'icon'=>'bi-shield-lock', 'url'=>route('network.index',['type'=>'watchguard'])],
        'networks' => ['label'=>'Redes empresariales', 'description'=>'SSID, VLAN y ubicaciones', 'count'=>$stats['networks'], 'icon'=>'bi-wifi', 'url'=>route('network.index',['type'=>'networks'])],
    ]" />
    <form class="table-filters network-filters" method="GET"><input type="hidden" name="type" value="{{ $type }}"><label><span>Buscar</span><input name="search" value="{{ $search }}" placeholder="Nombre, IP, MAC, area o ubicacion..."></label>@if($type === 'devices')<label><span>Estado</span><select name="status"><option value="">Todos</option>@foreach(['Activo','Inactivo','Mantenimiento','Desconocido'] as $option)<option value="{{ $option }}" @selected($status === $option)>{{ $option }}</option>@endforeach</select></label>@endif<button class="button button-secondary">Aplicar</button>@if($search !== '' || $status !== '')<a class="button button-secondary" href="{{ route('network.index', ['type'=>$type]) }}">Limpiar</a>@endif</form>
    <div class="table-scroll"><table>
    @if($type === 'devices')<thead><tr><th>Dispositivo</th><th>Tipo</th><th>IP</th><th>MAC</th><th>Ubicacion</th><th data-filterable="true">Estado</th><th></th></tr></thead><tbody>@forelse($items as $item)<tr><td><strong>{{ $item->device_name }}</strong><small>{{ $item->brand ?: 'Sin marca' }}</small></td><td>{{ $item->device_type ?: '-' }}</td><td>{{ $item->ip_address ?: '-' }}</td><td>{{ $item->mac_address ?: '-' }}</td><td>{{ $item->location ?: '-' }}</td><td><span class="status">{{ $item->status }}</span></td><td><div class="row-actions"><a class="table-action" href="{{ route('network-devices.show',$item) }}">Detalles</a>@can('update',$item)<a class="table-action secondary" href="{{ route('network-devices.edit',$item) }}">Editar</a>@endcan</div></td></tr>@empty<tr><td colspan="7" class="empty">No hay dispositivos para estos filtros.</td></tr>@endforelse</tbody>
    @elseif($type === 'watchguard')<thead><tr><th>Usuario</th><th>Asignado a</th><th>Area</th><th>IP</th><th>Actualizado</th><th></th></tr></thead><tbody>@forelse($items as $item)<tr><td><strong>{{ $item->username }}</strong></td><td>{{ $item->assigned_to ?: '-' }}</td><td>{{ $item->area ?: '-' }}</td><td>{{ $item->ip ?: '-' }}</td><td>{{ $item->updated_at?->format('d/m/Y H:i') }}</td><td><div class="row-actions"><a class="table-action" href="{{ route('watchguard-users.show',$item) }}">Detalles</a>@can('update',$item)<a class="table-action secondary" href="{{ route('watchguard-users.edit',$item) }}">Editar</a>@endcan</div></td></tr>@empty<tr><td colspan="6" class="empty">No hay usuarios para esta busqueda.</td></tr>@endforelse</tbody>
    @else <thead><tr><th>Red / SSID</th><th>VLAN</th><th>Ubicacion</th><th>Cifrado</th><th>Actualizada</th><th></th></tr></thead><tbody>@forelse($items as $item)<tr><td><strong>{{ $item->network_name }}</strong></td><td>{{ $item->vlan ?: '-' }}</td><td>{{ $item->location ?: '-' }}</td><td>{{ $item->encryption ?: '-' }}</td><td>{{ $item->updated_at?->format('d/m/Y H:i') }}</td><td><div class="row-actions"><a class="table-action" href="{{ route('enterprise-networks.show',$item) }}">Detalles</a>@can('update',$item)<a class="table-action secondary" href="{{ route('enterprise-networks.edit',$item) }}">Editar</a>@endcan</div></td></tr>@empty<tr><td colspan="6" class="empty">No hay redes para esta busqueda.</td></tr>@endforelse</tbody>@endif
    </table></div>
    @if($items->hasPages())<nav class="pagination">@if($items->onFirstPage())<span>Anterior</span>@else<a href="{{ $items->previousPageUrl() }}">Anterior</a>@endif<strong>Pagina {{ $items->currentPage() }} de {{ $items->lastPage() }}</strong>@if($items->hasMorePages())<a href="{{ $items->nextPageUrl() }}">Siguiente</a>@else<span>Siguiente</span>@endif</nav>@endif
</section>
@endsection
