<?php
namespace App\Http\Controllers;
use App\Models\CalendarReminder; use App\Services\AuditLogger; use Carbon\Carbon; use Illuminate\Http\RedirectResponse; use Illuminate\Http\Request; use Illuminate\View\View;
class CalendarReminderController extends Controller
{
 public function index(Request $r):View{$this->authorize('viewAny',CalendarReminder::class);$month=preg_match('/^\d{4}-\d{2}$/',(string)$r->query('month'))?$r->query('month'):now()->format('Y-m');$start=Carbon::createFromFormat('!Y-m',$month)->startOfMonth();$month=$start->format('Y-m');$items=CalendarReminder::whereBetween('event_date',[$start,$start->copy()->endOfMonth()])->orderBy('event_date')->get()->groupBy(fn($x)=>$x->event_date->format('Y-m-d'));$upcoming=CalendarReminder::whereDate('event_date','>=',today())->orderBy('event_date')->limit(10)->get();return view('calendar.index',compact('items','upcoming','start','month'));}
 public function create(Request $r):View{$this->authorize('create',CalendarReminder::class);$m=new CalendarReminder(['event_date'=>$r->query('date')]);return view('calendar.form',['calendarReminder'=>$m]);}
 public function store(Request $r,AuditLogger $a):RedirectResponse{$this->authorize('create',CalendarReminder::class);$m=CalendarReminder::create($this->data($r));$a->record('create','calendar_reminders',$m->id,null,$m->getAttributes());return redirect()->route('calendar.index',['month'=>$m->event_date->format('Y-m')])->with('success','Recordatorio creado.');}
 public function edit(CalendarReminder $calendarReminder):View{$this->authorize('update',$calendarReminder);return view('calendar.form',compact('calendarReminder'));}
 public function update(Request $r,CalendarReminder $calendarReminder,AuditLogger $a):RedirectResponse{$this->authorize('update',$calendarReminder);$before=$calendarReminder->getAttributes();$calendarReminder->update($this->data($r));$a->record('update','calendar_reminders',$calendarReminder->id,$before,$calendarReminder->fresh()->getAttributes());return redirect()->route('calendar.index',['month'=>$calendarReminder->event_date->format('Y-m')])->with('success','Recordatorio actualizado.');}
 public function destroy(CalendarReminder $calendarReminder,AuditLogger $a):RedirectResponse{$this->authorize('delete',$calendarReminder);$before=$calendarReminder->getAttributes();$month=$calendarReminder->event_date->format('Y-m');$calendarReminder->delete();$a->record('delete','calendar_reminders',$calendarReminder->id,$before,null);return redirect()->route('calendar.index',['month'=>$month])->with('success','Recordatorio eliminado.');}
 private function data(Request $r):array{$r->merge(['is_done'=>$r->boolean('is_done')]);return $r->validate(['event_date'=>['required','date'],'title'=>['required','string','max:255'],'color'=>['required','regex:/^#[0-9A-Fa-f]{6}$/'],'description'=>['nullable','string'],'comments'=>['nullable','string'],'is_done'=>['boolean']]);}
}
