<?php
namespace App\Http\Controllers;
use App\Models\AuditLog; use App\Models\GalleryItem; use App\Services\AuditLogger; use App\Services\LibraryFile; use Illuminate\Http\RedirectResponse; use Illuminate\Http\Request; use Illuminate\Support\Facades\Storage; use Illuminate\Support\Str; use Illuminate\View\View; use Symfony\Component\HttpFoundation\BinaryFileResponse;
class GalleryController extends Controller
{
 public function index(Request $r):View{$this->authorize('viewAny',GalleryItem::class);$query=GalleryItem::query();if($r->query('recent')==='updated'){$lastUpdate=AuditLog::select('created_at')->where('entity','gallery')->where('action','update')->whereColumn('entity_id','gallery.id')->latest('created_at')->limit(1);$query->orderByDesc($lastUpdate)->latest('upload_date');}else{$query->latest('upload_date');}return view('gallery.index',['items'=>$query->paginate(18)->withQueryString()]);}
 public function create():View{$this->authorize('create',GalleryItem::class);return view('gallery.form',['galleryItem'=>new GalleryItem]);}
 public function store(Request $r,AuditLogger $a):RedirectResponse{$this->authorize('create',GalleryItem::class);$d=$this->data($r,true);$f=$r->file('image');$path=$f->storeAs('library/gallery',now()->format('YmdHis').'-'.Str::uuid().'.'.strtolower($f->extension()),'local');$m=GalleryItem::create(['title'=>$d['title'],'notes'=>$d['notes']??null,'filename'=>'laravel-local:'.$path]);$a->record('create','gallery',$m->id,null,$m->getAttributes());return redirect()->route('gallery.show',$m)->with('success','Imagen agregada.');}
 public function show(GalleryItem $galleryItem):View{$this->authorize('view',$galleryItem);$auditLogs=request()->user()->can('viewAudit',$galleryItem)?AuditLog::where('entity','gallery')->where('entity_id',(string)$galleryItem->id)->latest()->limit(20)->get():collect();return view('gallery.show',compact('galleryItem','auditLogs'));}
 public function edit(GalleryItem $galleryItem):View{$this->authorize('update',$galleryItem);return view('gallery.form',compact('galleryItem'));}
 public function update(Request $r,GalleryItem $galleryItem,AuditLogger $a,LibraryFile $files):RedirectResponse{$this->authorize('update',$galleryItem);$before=$galleryItem->getAttributes();$d=$this->data($r,false);if($r->hasFile('image')){$f=$r->file('image');$path=$f->storeAs('library/gallery',now()->format('YmdHis').'-'.Str::uuid().'.'.strtolower($f->extension()),'local');$files->delete($galleryItem->filename,'uploads/gallery');$d['filename']='laravel-local:'.$path;}unset($d['image']);$galleryItem->update($d);$a->record('update','gallery',$galleryItem->id,$before,$galleryItem->fresh()->getAttributes());return redirect()->route('gallery.show',$galleryItem)->with('success','Imagen actualizada.');}
 public function image(GalleryItem $galleryItem,LibraryFile $files):BinaryFileResponse{$this->authorize('view',$galleryItem);return response()->file($files->path($galleryItem->filename,'uploads/gallery'));}
 public function destroy(GalleryItem $galleryItem,AuditLogger $a,LibraryFile $files):RedirectResponse{$this->authorize('delete',$galleryItem);$before=$galleryItem->getAttributes();$files->delete($galleryItem->filename,'uploads/gallery');$galleryItem->delete();$a->record('delete','gallery',$galleryItem->id,$before,null);return redirect()->route('gallery.index')->with('success','Imagen eliminada.');}
 private function data(Request $r,bool $required):array{return $r->validate(['title'=>['required','string','max:255'],'notes'=>['nullable','string'],'image'=>[$required?'required':'nullable','image','mimes:jpg,jpeg,png,gif,webp','max:15360']]);}
}
