<?php
namespace App\Http\Controllers;
use App\Models\AuditLog; use App\Models\Tutorial; use App\Services\AuditLogger; use App\Services\LibraryFile; use App\Support\RecentRecords; use Illuminate\Http\RedirectResponse; use Illuminate\Http\Request; use Illuminate\Support\Facades\DB; use Illuminate\Support\Facades\Storage; use Illuminate\Support\Str; use Illuminate\View\View; use Symfony\Component\HttpFoundation\BinaryFileResponse;
class TutorialController extends Controller
{
 public function index(Request $r):View{$this->authorize('viewAny',Tutorial::class);$s=trim((string)$r->query('search'));$query=Tutorial::query()->when($s!=='',fn($q)=>$q->where(fn($q)=>$q->where('title','like','%'.$s.'%')->orWhere('category','like','%'.$s.'%')->orWhere('description','like','%'.$s.'%')));$items=RecentRecords::apply($query,$r,fn($q)=>$q->latest())->paginate(18)->withQueryString();return view('tutorials.index',compact('items','s'));}
 public function create():View{$this->authorize('create',Tutorial::class);return view('tutorials.form',['tutorial'=>new Tutorial]);}
 public function store(Request $r,AuditLogger $a):RedirectResponse{$this->authorize('create',Tutorial::class);$d=$this->validateData($r,true);$file=$r->file('pdf_file');$path=$file->storeAs('library/tutorials',now()->format('YmdHis').'-'.Str::uuid().'.pdf','local');$d['content_url']='laravel-local:'.$path;unset($d['pdf_file']);$m=DB::transaction(function()use($d,$a){$m=Tutorial::create($d);$a->record('create','tutorials',$m->id,null,$m->getAttributes());return $m;});return redirect()->route('tutorials.show',$m)->with('success','Tutorial registrado.');}
 public function show(Tutorial $tutorial):View{$this->authorize('view',$tutorial);$auditLogs=request()->user()->can('viewAudit',$tutorial)?AuditLog::where('entity','tutorials')->where('entity_id',(string)$tutorial->id)->latest()->limit(20)->get():collect();return view('tutorials.show',compact('tutorial','auditLogs'));}
 public function edit(Tutorial $tutorial):View{$this->authorize('update',$tutorial);return view('tutorials.form',compact('tutorial'));}
 public function update(Request $r,Tutorial $tutorial,AuditLogger $a,LibraryFile $files):RedirectResponse{$this->authorize('update',$tutorial);$before=$tutorial->getAttributes();$d=$this->validateData($r,false);unset($d['pdf_file']);if($r->hasFile('pdf_file')){$path=$r->file('pdf_file')->storeAs('library/tutorials',now()->format('YmdHis').'-'.Str::uuid().'.pdf','local');if($tutorial->content_url)$files->delete($tutorial->content_url,'uploads/tutorials');$d['content_url']='laravel-local:'.$path;}DB::transaction(function()use($tutorial,$d,$before,$a){$tutorial->update($d);$a->record('update','tutorials',$tutorial->id,$before,$tutorial->fresh()->getAttributes());});return redirect()->route('tutorials.show',$tutorial)->with('success','Tutorial actualizado.');}
 public function preview(Tutorial $tutorial,LibraryFile $files):BinaryFileResponse{$this->authorize('view',$tutorial);abort_unless($tutorial->content_url,404);return response()->file($files->path($tutorial->content_url,'uploads/tutorials'),['Content-Type'=>'application/pdf','X-Content-Type-Options'=>'nosniff']);}
 public function download(Tutorial $tutorial,LibraryFile $files):BinaryFileResponse{$this->authorize('view',$tutorial);abort_unless($tutorial->content_url,404);return response()->download($files->path($tutorial->content_url,'uploads/tutorials'),Str::slug($tutorial->title).'.pdf',['Content-Type'=>'application/pdf']);}
 public function destroy(Tutorial $tutorial,AuditLogger $a,LibraryFile $files):RedirectResponse{$this->authorize('delete',$tutorial);$before=$tutorial->getAttributes();if($tutorial->content_url)$files->delete($tutorial->content_url,'uploads/tutorials');$tutorial->delete();$a->record('delete','tutorials',$tutorial->id,$before,null);return redirect()->route('tutorials.index')->with('success','Tutorial eliminado.');}
 private function validateData(Request $r,bool $required):array{return $r->validate(['title'=>['required','string','max:255'],'category'=>['nullable','string','max:100'],'description'=>['nullable','string'],'comments'=>['nullable','string'],'pdf_file'=>[$required?'required':'nullable','file','mimes:pdf','max:30720']]);}
}
