@extends('layouts.app') @section('title','Correos') @section('page-title','Control de correos') @section('content')
<section class="page-intro compact"><div><p class="eyebrow">Mensajeria empresarial</p><h2>Correos y reenvios</h2><p>Suscripciones Microsoft 365, cuentas Windows e historial de respaldos.</p></div><div class="page-actions"><x-recent-filter />@if($type==='microsoft')@can('create',\App\Models\MicrosoftEmail::class)<a class="button button-primary" href="{{route('microsoft-emails.create')}}">Nueva cuenta 365</a>@endcan @elseif($type==='windows')@can('create',\App\Models\OfficeEmail::class)<a class="button button-primary" href="{{route('office-emails.create')}}">Nuevo correo</a>@endcan @else @can('create',\App\Models\EmailBackup::class)<a class="button button-primary" href="{{route('email-backups.create')}}">Nuevo reenvio</a>@endcan @endif</div></section>
<section class="stats-grid credential-stats"><article><span>Microsoft 365</span><strong>{{$stats['microsoft']}}</strong><small>Suscripciones</small></article><article><span>Windows</span><strong>{{$stats['windows']}}</strong><small>Cuentas en equipos</small></article><article><span>Reenvios</span><strong>{{$stats['backups']}}</strong><small>Procesos registrados</small></article><article><span>Pendientes</span><strong>{{$stats['pending']}}</strong><small>Por completar</small></article></section>
<section class="panel table-panel"><x-module-tabs :active="$type" label="Tipo de correo" :tabs="[
    'microsoft' => ['label'=>'Microsoft 365', 'description'=>'Suscripciones corporativas', 'count'=>$stats['microsoft'], 'icon'=>'bi-microsoft', 'url'=>route('emails.index',['type'=>'microsoft'])],
    'windows' => ['label'=>'Correos Windows', 'description'=>'Cuentas configuradas en equipos', 'count'=>$stats['windows'], 'icon'=>'bi-windows', 'url'=>route('emails.index',['type'=>'windows'])],
    'backups' => ['label'=>'Reenvios', 'description'=>'Respaldos e historial de cuentas', 'count'=>$stats['backups'], 'icon'=>'bi-arrow-repeat', 'url'=>route('emails.index',['type'=>'backups'])],
]" />
<form class="table-filters credential-filters" method="GET"><input type="hidden" name="type" value="{{$type}}"><label><span>Buscar</span><input name="search" value="{{$search}}" placeholder="Correo, persona o comentario..."></label><label><span>Estado</span><select name="status"><option value="">Todos</option>@foreach($statusOptions as $option)<option value="{{ $option }}" @selected($status === $option)>{{ $type === 'backups' ? ['pending'=>'Pendientes','done'=>'Hechos','archived'=>'Archivados'][$option] : $option }}</option>@endforeach</select></label><button class="button button-secondary">Aplicar</button>@if($search!==''||$status!=='')<a class="button button-secondary" href="{{route('emails.index',['type'=>$type])}}">Limpiar</a>@endif</form>
<div class="table-scroll"><table>@if($type==='backups')<thead><tr><th>Cuenta original</th><th>Cuenta destino</th><th>Inicio</th><th>Fin</th><th>Estado</th><th></th></tr></thead><tbody>@forelse($items as $item)<tr><td><strong>{{$item->original_email}}</strong><small>{{$item->original_name}}</small></td><td><strong>{{$item->backup_email}}</strong><small>{{$item->backup_name}}</small></td><td>{{$item->dateLabel('start_date')?:'-'}}</td><td>{{$item->dateLabel('end_date')?:'-'}}</td><td><span class="status">{{$item->is_archived?'Archivado':($item->is_done?'Hecho':'Pendiente')}}</span></td><td><div class="row-actions"><a class="table-action" href="{{route('email-backups.show',$item)}}">Detalles</a>@can('update',$item)<a class="table-action secondary" href="{{route('email-backups.edit',$item)}}">Editar</a>@endcan</div></td></tr>@empty<tr><td colspan="6" class="empty">No hay reenvios para estos filtros.</td></tr>@endforelse</tbody>@else<thead><tr><th>Correo</th><th>Estado</th><th>Activacion</th><th>Renovacion</th>@if($type==='microsoft')<th>Administracion</th>@endif<th></th></tr></thead><tbody>@forelse($items as $item)<tr><td><strong>{{$item->email}}</strong></td><td><span class="status">{{$item->status}}</span></td><td>{{$item->dateLabel('activation_date')?:'-'}}</td><td>{{$item->dateLabel('renewal_date')?:'-'}}</td>@if($type==='microsoft')<td>{{$item->admin_account?:'-'}}</td>@endif<td><div class="row-actions"><a class="table-action" href="{{route($type==='microsoft'?'microsoft-emails.show':'office-emails.show',$item)}}">Detalles</a>@can('update',$item)<a class="table-action secondary" href="{{route($type==='microsoft'?'microsoft-emails.edit':'office-emails.edit',$item)}}">Editar</a>@endcan</div></td></tr>@empty<tr><td colspan="6" class="empty">No hay cuentas para estos filtros.</td></tr>@endforelse</tbody>@endif</table></div>
@if($items->hasPages())<nav class="pagination">@if($items->onFirstPage())<span>Anterior</span>@else<a href="{{$items->previousPageUrl()}}">Anterior</a>@endif<strong>Pagina {{$items->currentPage()}} de {{$items->lastPage()}}</strong>@if($items->hasMorePages())<a href="{{$items->nextPageUrl()}}">Siguiente</a>@else<span>Siguiente</span>@endif</nav>@endif</section>@endsection
