@extends('layouts.app')
@section('title','Empleados') @section('page-title','Empleados')
@section('content')
<section class="page-intro compact"><div><p class="eyebrow">Directorio interno</p><h2>{{ $employees->total() }} empleados encontrados</h2><p>Personas, departamentos y activos asignados.</p></div><div class="page-actions"><form method="GET" class="search-form"><label class="sr-only" for="search">Buscar empleados</label><input id="search" name="search" value="{{ $search }}" placeholder="Nombre, area, puesto, correo..."><button class="button button-secondary">Buscar</button>@if($search !== '')<a class="button button-secondary" href="{{ route('employees.index') }}">Limpiar</a>@endif</form><x-recent-filter />@can('create',\App\Models\Employee::class)<a class="button button-primary" href="{{ route('employees.create') }}">Nuevo empleado</a>@endcan</div></section>
<section class="panel table-panel"><div class="table-scroll"><table><thead><tr><th>Empleado</th><th>Departamento</th><th>Puesto</th><th>Correo</th><th>Celular</th><th>QR contacto</th><th>Activos</th><th data-filterable="true">Estado</th><th></th></tr></thead><tbody>
@forelse($employees as $employee)<tr><td><strong>{{ $employee->full_name }}</strong><small>{{ $employee->email_corporate ?: 'Sin correo' }}</small></td><td>{{ $employee->department ?: '-' }}</td><td>{{ $employee->position ?: '-' }}</td><td class="truncate">{{ $employee->email_corporate ?: '-' }}</td><td>{{ $employee->phone_number ?: '-' }}</td><td><img class="employee-qr" src="{{ $qrCodes[$employee->id] }}" alt="QR de contacto de {{ $employee->full_name }}" width="52" height="52" loading="lazy" title="Escanea para guardar el contacto"></td><td>{{ $employee->hardware_assets_count + $employee->cellphones_count + $employee->peripherals_count + $employee->printers_count }}</td><td><span class="status {{ $employee->status === 'Inactivo' ? 'status-muted' : '' }}">{{ $employee->status }}</span></td><td><div class="row-actions"><a class="table-action" href="{{ route('employees.show',$employee) }}">Detalles</a>@can('update',$employee)<a class="table-action secondary" href="{{ route('employees.edit',$employee) }}">Editar</a>@endcan</div></td></tr>
@empty<tr><td colspan="9" class="empty">No hay resultados para esta busqueda.</td></tr>@endforelse</tbody></table></div>
@if($employees->hasPages())<nav class="pagination">@if($employees->onFirstPage())<span>Anterior</span>@else<a href="{{ $employees->previousPageUrl() }}">Anterior</a>@endif<strong>Pagina {{ $employees->currentPage() }} de {{ $employees->lastPage() }}</strong>@if($employees->hasMorePages())<a href="{{ $employees->nextPageUrl() }}">Siguiente</a>@else<span>Siguiente</span>@endif</nav>@endif
</section>@endsection
